### ISSUE TITLE
Opening archives by dragging the file to the Fiji logo

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#16] opened 2020-09-10 13:00 UTC
When trying to open an archive by dragging the file to the Fiji logo two archives open: one with the file name in the header, one without. Also the Fiji log window displays an error and executing commands leads to a lot of crashes. It got so bad in the end that I had to force quit Fiji because it did not want to shut down because of all the errors raised.
Can you look into this and maybe either fix this or disable the dragging option?

**Comment by NadiaHuisjes** [comment] 2020-09-10 13:00
<img width="1215" alt="Screenshot 2020-09-10 at 14 58 11" src="https://user-images.githubusercontent.com/61824826/92732180-61292b80-f376-11ea-86d5-608263f71434.png">
<img width="582" alt="Screenshot 2020-09-10 at 14 58 19" src="https://user-images.githubusercontent.com/61824826/92732188-638b8580-f376-11ea-9476-58b42931b86e.png">

**Comment by karlduderstadt** [comment] 2020-09-10 13:06
Hi @NadiaHuisjes, 

Thank you very much for reporting this issue. Was SCIFIO turned on or off when you received this error? I noticed that I get the two windows when SCIFIO is turned off. When SCIFIO is turned on, everything works fine for me. Can you check this.

I mean globally turned on using the checkbox under edit>options...

**Comment by NadiaHuisjes** [comment] 2020-09-10 13:28
<img width="394" alt="Screenshot 2020-09-10 at 15 26 37" src="https://user-images.githubusercontent.com/61824826/92735836-0691ce80-f37a-11ea-83ea-b71dac2cae2c.png">

It seems that my SCIFIO is on (see screenshot) and I still observe the reported problem.

**Comment by karlduderstadt** [comment] 2020-09-10 14:47
I am not sure if it is possible to turn the drag and drop off. For me it just ones one window with no problems if scifio is turned on. If scifio is turned off I have the same problem as you. 

Maybe there is a mistake somewhere and/or workaround to prevent this issue. But I am still puzzled why I see differences with scifio on or off.

**Comment by karlduderstadt** [comment] 2020-09-11 14:19
For me, I only get this issue if SCIFIO is turned off. The issue is caused by this commit - https://github.com/fiji/IO/commit/e41e251c1bb6451267dd01321728f800074322b2

This commit is supposed to open files with SCIFIO turned off in the case no other readers are found. However, in our case this code creates the window twice. First it calls the open method and inside there I had a uiService.show( call that displayed the archive. However, in the same code above it also runs show. I guess there must be a mechanism whereby I don't have to call show directly in my IOPlugin open method, but inside the archive is show automatically. If such a mechanism exists that would fix the problem. I will start digging through scijava to see how other IOPlugins work in this regard.

**Comment by karlduderstadt** [comment] 2020-09-11 15:00
With mars-fx commit c5524de and related mars-core commit 36a569d now this issue is partially address. Now Open.. and Drag and Drop work as expected if SCIFIO is turned off. But they do not work if SCIFIO is turned on. Instead yamt, yama, and yama.store files are opened, but not displayed. So opening again will trigger an error.

I guess there must be a way to have SCIFIO display these files directly, but I can't seem to find the uiService.show( method that would do this anywhere. I will keep searching

**Comment by karlduderstadt** [comment] 2020-09-11 15:43
I posted on the ImageJ forum to see if they know the solution to this problem - https://forum.image.sc/t/open-a-custom-file-type-via-the-imagejs-open-dialog/41471/4

**Comment by karlduderstadt** [comment] 2020-09-11 19:58
It appears that when SCIFIO is turned on uiService.show(..) is never called and table as well as archive windows are never opened in the DefaultLegacyOpener in net.imagej.legacy.plugin. If SCIFIO is turned off then uiService.show(...) is called in https://github.com/fiji/IO/commit/e41e251c1bb6451267dd01321728f800074322b2 and windows are opened.

As a work around duderstadt-lab/mars-core@825cfb7 adds imagej-legacy dependency and then detects if SCIFIO is turned on or off. If it is turned on uiService.show(...) is called in the open methods of mars IOPlugins. If it is off uiService.show(...) is never called in mars and instead is called by https://github.com/fiji/IO/commit/e41e251c1bb6451267dd01321728f800074322b2.

This appears to fix the issue, so I am closing it for now. This workaround should be removed if the uiService.show(...) is added to the DefaultLegacyOpener .

**Closed by karlduderstadt** 2020-09-11 19:58 UTC
